#!/bin/bash

if [ "$1" == "-h" ]; then
    echo "This script assumes you are running your instance in an ASG with an ELB healthcheck."
    echo "It removes the instance from it's ELB and prevents shutdown, isolating the instance from requests."
    echo
    echo "Usage: `basename $0` instance-id load-balancer-id"
    echo
    exit 0
fi

INSTANCE_ID=$1
LOAD_BALANCER_ID=$2

aws ec2 modify-instance-attribute --instance-id $INSTANCE_ID --disable-api-termination --profile media-service
aws elb deregister-instances-from-load-balancer --load-balancer-name $LOAD_BALANCER_ID --instances $INSTANCE_ID 
