#!/bin/bash

if [ "$1" == "-h" ]; then
    echo "This script disables termination protection for an instance and then terminates it."
    echo
    echo "Usage: `basename $0` instance-id decrement [optional]"
    echo
    exit 0
fi

INSTANCE_ID=$1
ASG_NAME=`aws autoscaling describe-auto-scaling-instances --instance-ids i-0da256f4 | jq -r ".AutoScalingInstances[0].AutoScalingGroupName"`

echo "Terminating $INSTANCE_ID in $ASG_NAME"

if [ "$2" = "decrement" ]; then
    echo "This action will decrement desired capacity"
    ACTION="--should-decrement-desired-capacity"
fi

read -p "Are you sure? (y/n)" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    aws ec2 modify-instance-attribute --instance-id $INSTANCE_ID --no-disable-api-termination --profile media-service
    aws autoscaling terminate-instance-in-auto-scaling-group --instance-id $INSTANCE_ID $ACTION --profile media-service
fi
